"""Extract keynotes / ceremonies / socials from the program-at-a-glance grid.

CAVEAT — read before trusting the output.

The at-a-glance grid exists only in the superseded 2026-09-08 PDF; the current
2026-09-10 program dropped it.  Two consequences:

  1. The times are STALE.  Poster sessions 3 and 5 sit at 16:00 in this grid but
     at 15:30 in the authoritative 2026-09-10 program, so other rows may have
     moved too.
  2. A label inside a tall merged cell is vertically centred, so the row it
     lands on is the MIDDLE of the event, not its start.  The Gala Dinner shows
     up at 21:00 while its own label reads "7:00 pm - 11:00 pm".

Output is therefore a REVIEW DRAFT written to config/program-events.yaml, with
every entry flagged, for a human to confirm or correct.  Nothing here is fed
into program.json as authoritative.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import fitz
import yaml

sys.path.insert(0, str(Path(__file__).parent))
from common import fold, slug

DAY_DATES = {"Monday": "2026-09-28", "Tuesday": "2026-09-29", "Wednesday": "2026-09-30"}
SKIP = re.compile(
    r"^(Oral|Poster|Coffee Break|Lunch|P\d$|WiM$|RISE$|PaRTNER$|SIG Presentations|CLINICCAI)",
    re.I)
KEEP = re.compile(
    r"Keynote|Ceremony|Gala|Awards|Panel|Assembly|Morning Run|Football|Networking|"
    r"Area Chairs|Board Candidate|Thesis|Open Data|Sponsorship", re.I)


def parse(pdf: Path) -> list[dict]:
    doc = fitz.open(pdf)
    table = doc[0].find_tables().tables[0]
    rows = table.extract()

    day_of_col: dict[int, str] = {}
    current = None
    for ci, cell in enumerate(rows[0]):
        m = re.search(r"(Monday|Tuesday|Wednesday)", cell or "")
        if m:
            current = m.group(1)
        if current:
            day_of_col[ci] = current

    seen: set[tuple] = set()
    out: list[dict] = []
    for row in rows[1:]:
        time = (row[0] or "").strip()
        if not re.fullmatch(r"\d{1,2}:\d{2}", time):
            continue
        for ci, cell in enumerate(row[1:], 1):
            text = fold(" ".join((cell or "").split()))
            if not text or SKIP.match(text) or not KEEP.search(text):
                continue
            day = day_of_col.get(ci)
            if not day:
                continue
            key = (day, text)
            if key in seen:
                continue
            seen.add(key)
            hh, mm = time.split(":")
            # An explicit clock range inside the label always beats the row.
            explicit = re.search(r"\((\d{1,2}):(\d{2})\s*(am|pm)?\s*-\s*(\d{1,2}):(\d{2})\s*(am|pm)?\)",
                                 text, re.I)
            out.append({
                "id": f"{slug(day)}-{slug(text)[:40]}",
                "name": text,
                "date": DAY_DATES[day],
                "grid_row_time": f"{int(hh):02d}:{mm}",
                "label_time_range": explicit.group(0) if explicit else None,
                "start": None,       # <- to be filled in by a human
                "end": None,
                "room": None,
                "needs_review": True,
            })
    return out


if __name__ == "__main__":
    events = parse(Path("data/raw/superseded/main-program-rev2026-09-08.pdf"))
    dest = Path("config/program-events.yaml")
    dest.write_text(
        "# REVIEW DRAFT — generated by scripts/parse_glance.py from the SUPERSEDED\n"
        "# 2026-09-08 at-a-glance grid (the 2026-09-10 program dropped that page).\n"
        "#\n"
        "# grid_row_time is the row the label was printed on. For a tall merged cell\n"
        "# that is the MIDDLE of the event, not its start. Poster sessions moved by\n"
        "# 30 min between 09-08 and 09-10, so treat every time here as unconfirmed.\n"
        "#\n"
        "# Fill in start/end (and room) by hand, then set needs_review: false.\n"
        "# Only entries with needs_review: false are emitted into program.json.\n\n"
        + yaml.safe_dump(events, sort_keys=False, allow_unicode=True, width=100),
        encoding="utf-8")
    print(f"wrote {dest} with {len(events)} draft entries")
    for e in events:
        print(f'  {e["date"]}  ~{e["grid_row_time"]}  {e["name"][:66]}')
